"""Add ReadAlbum

Revision ID: 2908c1070d9e
Revises: 1c97e89fdefd
Create Date: 2014-05-01 01:29:47.747071

"""

# revision identifiers, used by Alembic.
revision = '2908c1070d9e'
down_revision = '1c97e89fdefd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_albums',
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_albums')
    ### end Alembic commands ###
