"""Add album

Revision ID: 4d255e72ec0e
Revises: None
Create Date: 2014-03-13 13:03:20.433320

"""

# revision identifiers, used by Alembic.
revision = '4d255e72ec0e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
