"""add artist

Revision ID: 58ef68fbe360
Revises: 9f832c9f4c6
Create Date: 2014-03-18 21:32:57.525065

"""

# revision identifiers, used by Alembic.
revision = '58ef68fbe360'
down_revision = '9f832c9f4c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('link', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('cover', sa.Unicode(), nullable=True),
    sa.Column('link', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    op.drop_table('artists')
    ### end Alembic commands ###
